 ./corewar lf.cor zj.cor zork.cor > /dev/null
 ./corewar lf.cor zj.cor zork.cor > /dev/null
 ./corewar lf.cor zj.cor zork.cor > /dev/null
 ./corewar lf.cor zj.cor zork.cor > /dev/null
 ./corewar lf.cor zj.cor zork.cor > /dev/null
 ./corewar lf.cor zj.cor zork.cor > /dev/null
 ./corewar lf.cor zj.cor zork.cor > /dev/null
 ./corewar lf.cor zj.cor zork.cor > /dev/null
 ./corewar lf.cor zj.cor zork.cor > /dev/null
 ./corewar lf.cor zj.cor zork.cor > /dev/null
 ./corewar lf.cor zj.cor zork.cor > /dev/null
 ./corewar lf.cor zj.cor zork.cor > /dev/null
 ./corewar lf.cor zj.cor zork.cor > /dev/null
 ./corewar lf.cor zj.cor zork.cor > /dev/null
 ./corewar lf.cor zj.cor zork.cor > /dev/null
 ./corewar lf.cor zj.cor zork.cor > /dev/null
 ./corewar lf.cor zj.cor zork.cor > /dev/null
 ./corewar lf.cor zj.cor zork.cor > /dev/null
 ./corewar lf.cor zj.cor zork.cor > /dev/null
 ./corewar lf.cor zj.cor zork.cor > /dev/null
